<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LT012489" name="Test" tests="4" failures="1" timestamp="8 Feb 2013 10:38:22 GMT" time="48.946" errors="0">
  <testcase name="runTC1" time="11.603" classname="testscripts.Scenario1"/>
  <testcase name="runTC2" time="19.475" classname="testscripts.Scenario1"/>
  <testcase name="runTC3" time="33.976" classname="testscripts.Scenario1">
    <failure type="java.lang.AssertionError" message="Login failed for valid user">
      <![CDATA[java.lang.AssertionError: Login failed for valid user
	at supportlibraries.DriverScript.wrapUp(DriverScript.java:515)
	at supportlibraries.DriverScript.driveTestExecution(DriverScript.java:88)
	at testscripts.Scenario1.runTC3(Scenario1.java:56)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- runTC3 -->
  <testcase name="runTC4" time="48.936" classname="testscripts.Scenario2"/>
</testsuite> <!-- Test -->
